version: '3.7'
services:
  postgres:
    image: clkao/postgres-plv8:latest
    environment:
      POSTGRES_USER: scrabblehero
      POSTGRES_PASSWORD: password
      POSTGRES_DB: production
    ports:
      - '5432:5432'
  api:
    build: ./docker/api
    volumes:
      - ./docker/api:/app
      - ./data:/app/data
    ports:
      - '5000:5000'
    command: flask run --host 0.0.0.0 --port 5000
    environment:
      DATABASE_URL: postgresql://scrabblehero:password@postgres:5432/production
      FLASK_ENV: development
  www:
    build: ./docker/www
    volumes:
      - ./docker/www:/app
      - ./data:/app/data
      - /app/node_modules
    ports:
      - '8080:8080'
