"""Add words table

Revision ID: 204d610a3628
Revises:
Create Date: 2019-12-02 01:15:30.759556

"""
import datetime as dt

from alembic import op
import sqlalchemy as sa
from flask import current_app

from app.utils import WordGenerator

word_generator = WordGenerator()

# revision identifiers, used by Alembic.
revision = '204d610a3628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
        sa.Column('value', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
