"""Add words table

Revision ID: 204d610a3628
Revises:
Create Date: 2019-12-02 01:15:30.759556

"""
import datetime as dt

from alembic import op
import sqlalchemy as sa
from flask import current_app

from app.utils import WordGenerator

word_generator = WordGenerator()

# revision identifiers, used by Alembic.
revision = '204d610a3628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    word_table = op.create_table('word',
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
        sa.Column('value', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('value')
    )
    current_app.logger.info("Created table")
    words = word_generator.generate_words()
    current_app.logger.info("Generated words")
    created_at = updated_at = dt.datetime.now()
    for word in words:
        word.update({'created_at': created_at, 'updated_at': updated_at})
    else:
        current_app.logger.info("Updated fields on words")
    op.bulk_insert(word_table, words)
    current_app.logger.info("Finished inserting words")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
