"""Add score to word

Revision ID: a92d027328dd
Revises: 409c447e7fa5
Create Date: 2019-12-02 22:39:26.622316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92d027328dd'
down_revision = '409c447e7fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('score', sa.Integer(), nullable=True))
    op.execute("update word set score=score(word.value)")
    op.execute("alter table word alter score set not null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'score')
    # ### end Alembic commands ###
