"""Add indexes

Revision ID: d8f5961bcc69
Revises: ea246209833b
Create Date: 2019-12-12 02:17:35.130739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f5961bcc69'
down_revision = 'ea246209833b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_word_anagram_hash'), 'word', ['anagram_hash'], unique=False)
    op.create_index(op.f('ix_word_length'), 'word', ['length'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_length'), table_name='word')
    op.drop_index(op.f('ix_word_anagram_hash'), table_name='word')
    # ### end Alembic commands ###
