"""Add definitions to word

Revision ID: dc7b5d179e81
Revises: d8f5961bcc69
Create Date: 2019-12-14 16:48:51.870504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7b5d179e81'
down_revision = 'd8f5961bcc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('definition', sa.String(), nullable=True))
    op.execute("update word set definition='pending'")
    op.execute('alter table word alter column definition set not null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'definition')
    # ### end Alembic commands ###
