name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start
      run: docker-compose up --detach && docker-compose ps && docker-compose logs www
    - name: Test
      run: docker-compose exec -T api pytest
    - name: Deploy api
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: scrabble-hero-production
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
    - name: Build
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: docker-compose exec -T www npm run build
    - name: Deploy www
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'docker/www/dist'
