name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start
      run: docker-compose up --detach && docker-compose exec -T api flask db upgrade
    - name: Seed
      run: docker-compose exec -T api flask seed words
    - name: Test
      run: docker-compose exec -T api pytest
    - name: Deploy api
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: scrabble-hero-production
      run: |
        docker tag scrabblehero_api registry.heroku.com/scrabble-hero-production/web
        docker tag scrabblehero_release registry.heroku.com/scrabble-hero-production/release
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker push registry.heroku.com/scrabble-hero-production/web
        docker push registry.heroku.com/scrabble-hero-production/release
        heroku container:release --app $HEROKU_APP_NAME web release
    - name: Build
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: docker-compose exec -T www npm run build
    - name: Deploy www
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'docker/www/dist'
    - name: Invalidate cloudfront cache
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
